#!/bin/bash
# install-secure.sh: Initialize a secure, isolated WSL2 distro for agent execution.
#
# Run this INSIDE the dedicated secure distro (e.g., Ubuntu-secure), not in
# your normal development distro. Disables WSL-Windows interop, automount,
# and Windows PATH inheritance.
#
# Prerequisites:
#   - You created a separate WSL2 distro:
#       wsl --install -d Ubuntu-24.04 --name Ubuntu-secure
#   - You are inside that distro (verify: $WSL_DISTRO_NAME == Ubuntu-secure)
#   - This dotfiles repo is cloned at ~/dotfiles
#
# After running:
#   1. Exit the distro (`exit`)
#   2. From Windows: `wsl --shutdown`
#   3. Reopen the secure distro — interop and automount will be disabled

set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

# ==============================================================================
# Color output helpers
# ==============================================================================
info()  { echo -e "\033[1;34m[INFO]\033[0m $*"; }
ok()    { echo -e "\033[1;32m[OK]\033[0m   $*"; }
warn()  { echo -e "\033[1;33m[WARN]\033[0m $*"; }
error() { echo -e "\033[1;31m[ERR]\033[0m  $*"; exit 1; }

# ==============================================================================
# Sanity checks
# ==============================================================================
if [[ -z "${WSL_DISTRO_NAME:-}" ]]; then
  error "Not running inside WSL. Run this script inside the secure WSL2 distro."
fi

if [[ "$WSL_DISTRO_NAME" == "Ubuntu" || "$WSL_DISTRO_NAME" == "Ubuntu-24.04" ]]; then
  warn "You are running inside '$WSL_DISTRO_NAME'."
  warn "This script is meant for a SEPARATE secure distro (e.g., Ubuntu-secure)."
  warn "Continuing will disable WSL-Windows integration in this distro."
  read -rp "Continue anyway? (yes/no): " confirm
  [[ "$confirm" == "yes" ]] || error "Aborted."
fi

# ==============================================================================
# 1. Install minimal packages
# ==============================================================================
info "Installing minimal package set..."
sudo apt update -qq
sudo apt install -y -qq \
  zsh \
  git \
  curl \
  wget \
  unzip \
  build-essential \
  jq \
  ca-certificates
ok "Minimal packages installed"

# ==============================================================================
# 2. Configure /etc/wsl.conf to disable Windows integration
# ==============================================================================
info "Writing /etc/wsl.conf to isolate from Windows..."

WSL_CONF="/etc/wsl.conf"
sudo tee "$WSL_CONF" > /dev/null <<EOF
# Generated by dotfiles install-secure.sh
# Isolates this WSL2 distro from Windows for agent safety.

[interop]
# Disable execution of Windows .exe files (no powershell.exe, cmd.exe, etc.)
enabled = false
# Don't append Windows PATH (no accidental access to Windows binaries)
appendWindowsPath = false

[automount]
# Don't auto-mount Windows drives (no /mnt/c, /mnt/d access)
enabled = false

[network]
# Generate /etc/resolv.conf normally
generateResolvConf = true

[user]
default = $USER

[boot]
# Don't run any Windows-side commands on boot
EOF

sudo chmod 644 "$WSL_CONF"
ok "/etc/wsl.conf written"

# ==============================================================================
# 3. Install Claude Code
# ==============================================================================
if ! command -v claude &> /dev/null; then
  info "Installing Claude Code..."
  curl -fsSL https://claude.ai/install.sh | bash
  export PATH="$HOME/.claude/bin:$HOME/.local/bin:$PATH"
fi
ok "Claude Code installed"

# ==============================================================================
# 4. Apply Claude Code safety layer (hooks, settings, scripts)
# ==============================================================================
info "Setting up Claude Code safety layer..."

CLAUDE_DIR="$HOME/.claude"
CLAUDE_HOOKS_DIR="$CLAUDE_DIR/hooks"
CLAUDE_SETTINGS="$CLAUDE_DIR/settings.json"
TEMPLATE="$DOTFILES_DIR/claude/settings.template.json"

mkdir -p "$CLAUDE_HOOKS_DIR" "$HOME/.local/bin"

ln -sf "$DOTFILES_DIR/claude/hooks/pre-tool-use.sh" "$CLAUDE_HOOKS_DIR/pre-tool-use.sh"
ln -sf "$DOTFILES_DIR/claude/scripts/safe-claude" "$HOME/.local/bin/safe-claude"
ln -sf "$DOTFILES_DIR/claude/scripts/claude-audit" "$HOME/.local/bin/claude-audit"

if [[ -f "$CLAUDE_SETTINGS" ]]; then
  info "Merging Claude Code safety settings..."
  MERGED="$(jq -s '
    (.[0].permissions.allow // []) as $tpl_allow |
    (.[1].permissions.allow // []) as $ext_allow |
    (.[0].permissions.deny // []) as $tpl_deny |
    (.[1].permissions.deny // []) as $ext_deny |
    (.[0].hooks // {}) as $tpl_hooks |
    (.[1].hooks // {}) as $ext_hooks |
    .[1] * {
      permissions: {
        allow: ($ext_allow + ($tpl_allow - $ext_allow)),
        deny: ($ext_deny + ($tpl_deny - $ext_deny))
      },
      hooks: (
        ($ext_hooks | keys) as $ek |
        ($tpl_hooks | keys) as $tk |
        ($ek + ($tk - $ek)) | unique | map(
          . as $key |
          if ($ext_hooks[$key] // null) != null and ($tpl_hooks[$key] // null) != null then
            {($key): (($ext_hooks[$key] // []) + (($tpl_hooks[$key] // []) | map(
              select(. as $item | ($ext_hooks[$key] // []) | map(.matcher == $item.matcher and .hooks == $item.hooks) | any | not)
            )))}
          elif ($tpl_hooks[$key] // null) != null then
            {($key): $tpl_hooks[$key]}
          else
            {($key): $ext_hooks[$key]}
          end
        ) | add // {}
      )
    }
  ' "$TEMPLATE" "$CLAUDE_SETTINGS")"
  echo "$MERGED" | jq '.' > "$CLAUDE_SETTINGS.tmp"
  mv "$CLAUDE_SETTINGS.tmp" "$CLAUDE_SETTINGS"
else
  cp "$TEMPLATE" "$CLAUDE_SETTINGS"
fi

ok "Claude Code safety layer configured"

# ==============================================================================
# 5. Optional: install full dotfiles (zsh, starship, etc.)
# ==============================================================================
echo ""
read -rp "Install full dotfiles (zsh, starship, modern CLI tools)? [y/N]: " install_full
if [[ "$install_full" == "y" || "$install_full" == "Y" ]]; then
  info "Running full install.sh (note: WSL-Windows integration features won't work)..."
  SKIP_UPGRADE=1 "$DOTFILES_DIR/install.sh"
fi

# ==============================================================================
# Done
# ==============================================================================
echo ""
echo -e "\033[1;32m========================================\033[0m"
echo -e "\033[1;32m  Secure distro setup complete.         \033[0m"
echo -e "\033[1;32m========================================\033[0m"
echo ""
echo "Next steps to apply isolation settings:"
echo ""
echo "  1. Exit this distro:    exit"
echo "  2. From Windows:        wsl --shutdown"
echo "  3. Reopen this distro:  wsl -d $WSL_DISTRO_NAME"
echo ""
echo "Verify isolation after restart:"
echo "  ls /mnt/c                 # should fail (no automount)"
echo "  powershell.exe -Command 1 # should fail (interop disabled)"
echo "  echo \$PATH | grep -i windows  # should be empty"
echo ""
